### PR TITLE
Added the police stations cameras

### PR DESCRIPTION
**Pull request by LifeGoal**

### CODE REVIEW

**Comment by xander1998** [comment]
Why did you add the police cameras to the bank cameras. You should have made the seperate..

**Comment by xander1998** [comment]
```
SecurityCamConfig = {}

SecurityCamConfig.DebugMode = false
SecurityCamConfig.HideRadar = true

SecurityCamConfig.Locations = {
    {
        camBox = {label = "Pacific Standard Bank", x = 283.67, y = 264.41, z = 105.80},
        cameras = {
            {label = "Bank Camera 1", x = 257.45, y = 210.07, z = 109.08, r = {x = -25.0, y = 0.0, z = 28.05}},
            {label = "Bank Camera 2", x = 269.66, y = 223.67, z = 113.23, r = {x = -30.0, y = 0.0, z = 111.29}},
            {label = "Bank Camera 3", x = 241.64, y = 233.83, z = 111.48, r = {x = -35.0, y = 0.0, z = 120.46}},
            {label = "Bank Camera 4", x = 232.86, y = 221.46, z = 107.83, r = {x = -25.0, y = 0.0, z = -140.91}},
            {label = "Bank Camera 5", x = 261.50, y = 218.08, z = 107.95, r = {x = -25.0, y = 0.0, z = -149.49}},
            {label = "Bank Camera 6", x = 261.98, y = 217.92, z = 113.25, r = {x = -40.0, y = 0.0, z = -159.49}},
            {label = "Bank Camera 7", x = 258.44, y = 204.97, z = 113.25, r = {x = -30.0, y = 0.0, z = 10.50}},
            {label = "Bank Camera 8", x = 235.53, y = 227.37, z = 113.23, r = {x = -35.0, y = 0.0, z = -160.29}},
            {label = "Bank Camera 9", x = 254.72, y = 206.06, z = 113.28, r = {x = -35.0, y = 0.0, z = 44.70}},
            {label = "Bank Camera 10", x = 269.89, y = 223.76, z = 106.48, r = {x = -35.0, y = 0.0, z = 112.62}},
            {label = "Bank Camera 11", x = 252.27, y = 225.52, z = 103.99, r = {x = -35.0, y = 0.0, z = -74.87}}
        },
        allowedModels = {}
    },
    {
        camBox = {label = "Los Santos Police Department", x = 283.67, y = 264.41, z = 105.80},
        cameras = {
            {label = "Police Camera 1", x = 416.744, y = -1009.270, z = 34.08, r = {x = -25.0, y = 0.0, z = 28.05}},
            {label = "Police Camera 2", x = 465.151, y = -994.266, z = 27.23, r = {x = -30.0, y = 0.0, z = 100.29}},
            {label = "Police Camera 3", x = 465.631, y = -997.777, z = 27.48, r = {x = -35.0, y = 0.0, z = 90.46}},
            {label = "Police Camera 4", x = 465.544, y = -1001.583, z = 27.1, r = {x = -25.0, y = 0.0, z = 90.01}},
            {label = "Police Camera 5", x = 420.241, y = -1009.010, z = 34.95, r = {x = -25.0, y = 0.0, z = 230.95}},
            {label = "Police Camera 6", x = 433.249, y = -977.786, z = 33.456, r = {x = -40.0, y = 0.0, z = 100.49}},
            {label = "Police Camera 7", x = 449.440, y = -987.639, z = 33.25, r = {x = -30.0, y = 0.0, z = 50.50}}
        },
        allowedModels = {}
    }
}
```

Obviously you would change the coordinates for the camBox table......

**Comment by LifeGoal** [comment]
Yeah I guess it was just something that would have made it easier for you

**Comment by LifeGoal** [comment]
The file is now fixed for you.

**Pull request closed without merging**
